/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import javax.swing.ImageIcon;

/**
 *
 * @author aweso
 */
public class Startup extends javax.swing.JFrame {

    /**
     * Creates new form Startup
     */
    
    ImageIcon bg = new ImageIcon(getClass().getClassLoader().getResource("Resources/BACKGROUND.jpg"));
    public Startup() {
        initComponents();
        jLabel2.setIcon(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPlayer1 = new javax.swing.JButton();
        jButtonPlayer2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPlayer1 = new javax.swing.JButton();
        jButtonPlayer2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Play Chess");
        getContentPane().setLayout(null);

        jButtonPlayer1.setText("Enter as Player 1");
        jButtonPlayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlayer1MouseClicked(evt);
            }
        });
        getContentPane().add(jButtonPlayer1);
        jButtonPlayer1.setBounds(290, 350, 249, 23);

        jButtonPlayer2.setText("Enter as Player 2");
        jButtonPlayer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlayer2MouseClicked(evt);
            }
        });
        getContentPane().add(jButtonPlayer2);
        jButtonPlayer2.setBounds(290, 380, 249, 23);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("PLAY CHESS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 170, 249, 45);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/BACKGROUND.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 834, 572);

        setSize(new java.awt.Dimension(857, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayer1MouseClicked

        MainFrame mn = new MainFrame("player1");
        this.show(false);
        mn.show(true);

    }//GEN-LAST:event_jButtonPlayer1MouseClicked

    private void jButtonPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayer2MouseClicked
        MainFrame mn = new MainFrame("player2");
        this.show(false);
        mn.show(true);
    }//GEN-LAST:event_jButtonPlayer2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlayer1;
    private javax.swing.JButton jButtonPlayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
